### ISSUE TITLE
How do I remove typescript?

### ISSUE THREAD

**Issue by Zaya6** [nodegui/nodegui-starter#33]
Is it possible to get a version of this without typescript or at least get some documentation on how to remove it? I'm not very versed in either typescript or webpack and all of my attempts to fix it have broken the project.

**Comment by master-atul** [comment]
Hi @Zaya6 

By default, nodegui-starter project is a typescript project. In order to convert our starter to a JS project you can make the following minor changes.

1. Delete the `index.ts` file that comes with the starter.
2. Create a new file `index.js`under the `src` directory with the following contents:

`src/index.js`

```js
const { QMainWindow, QLabel } = require("@nodegui/nodegui");

const win = new QMainWindow();
win.setWindowTitle("Meme Search");

const label = new QLabel();
label.setText("Hello World");

win.setCentralWidget(label);
win.show();

global.win = win;
```

Now run the app again:

```sh
npm start
```

**Comment by master-atul** [comment]
Please close the issue if this works for you.
